version: "3"
services:
    app:
        build: .
        container_name: serverapp
        restart: unless-stopped
        environment:
            APP_DEBUG: "True"
            APP_PORT: 5000
        ports:
          - '5000:5000'
